{% set name = "threddsclient" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be496da24b523f518818c98c9b901845bc9c6e6d0fef12b48f25e33efeeb63a3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - threddsclient

  requires:
    - pytest

about:
  home: https://github.com/bird-house/threddsclient
  license: Apache-2.0
  license_file: LICENCE.txt
  summary: 'Thredds catalog client in Python'
  doc_url: https://pypi.org/project/threddsclient/
  dev_url: https://github.com/bird-house/threddsclient

extra:
  recipe-maintainers:
    - cehbrecht
    - davidcaron
