{% set name = "threddsclient" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea5915347b24df95045422082d1157f5baee92ee4fabb5a45e2b4cf196881755

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - threddsclient

  requires:
    - pytest

about:
  home: https://github.com/bird-house/threddsclient
  license: Apache-2.0
  license_file: LICENCE.txt
  summary: Thredds catalog client in Python
  doc_url: https://pypi.org/project/threddsclient/
  dev_url: https://github.com/bird-house/threddsclient

extra:
  recipe-maintainers:
    - cehbrecht
    - davidcaron
